name: mobile

description: A new Flutter project.

publish_to: 'none'


environment:
  sdk: ^3.9.0



dependencies:

  flutter:
    sdk: flutter

  http: ^1.6.0

  shared_preferences: ^2.3.2

  provider: ^6.1.2

  image_picker: ^1.1.2