name: mobile

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  image_picker: ^1.1.2
  fl_chart: ^0.69.2
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  permission_handler: ^12.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon.png

  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/icon/icon.png