name: Build APK Flutter

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    name: Gerar APK Release

    runs-on: ubuntu-latest


    steps:


      - name: Baixar código
        uses: actions/checkout@v4



      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable
          cache: false



      - name: Ver versões
        run: |
          flutter --version
          java -version



      - name: Limpar projeto
        working-directory: mobile
        run: flutter clean



      - name: Instalar dependências
        working-directory: mobile
        run: flutter pub get



      - name: Gerar APK
        working-directory: mobile
        run: flutter build apk --release



      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk